### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by PaulineTreyvaud** [Pandede/WPODNet-Pytorch#19]
Hello @Pandede,

I see that you didn't set a license for this code. As the original repo for the keras implementation is under GPL license, does it also apply on this repo ?

Best
Pauline

**Comment by Pandede** [comment]
Sure, I may add it now. Thanks for your kindly reminding.

**Comment by Pandede** [comment]
[GPL-3.0 license](https://github.com/Pandede/WPODNet-Pytorch#GPL-3.0-1-ov-file) is added.

**Comment by PaulineTreyvaud** [comment]
Thank you for your reactivity

**Comment by PaulineTreyvaud** [comment]
Thank you for your reactivity
